linkpub_link_pub_gui_client:
    resource: "@LinkPubGuiBundle/Resources/config/routing-client.yml"
    prefix:   /user/

linkpub_link_pub_gui_guest:
    resource: "@LinkPubGuiBundle/Resources/config/routing-guest.yml"
    prefix:   /

link_pub_link_pub_user:
    resource: "@LinkPubUserBundle/Resources/config/routing.yml"
    prefix:   /

linkpub_link_pub_consumer:
    resource: "@LinkPubConsumerBundle/Resources/config/routing.yml"
    prefix:  /consumer
    
#FosUserBundle Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

vkontakte_login:
    pattern: /login/check-vkontakte

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


